### ISSUE TITLE
mmap over 4gb?

### ISSUE THREAD

**Issue by ccleve** [bnyeggen/lash#1]
I came across your blog post about mmapping files over 2 gb.

http://nyeggen.com/post/2014-05-18-memory-mapping-%3E2gb-of-data-in-java/

I tried it, and I get EXCEPTION_ACCESS_VIOLATION when I try to access a file position over 4gb.

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V+0

Have you actually gotten this to work with large files?

(I'm using a 64 bit JVM on Windows.)

**Comment by bnyeggen** [comment]
I have used it on 64 bit Linux & OS X successfully.  Googling that error I see it might be related to UAC (seems to be a recurring issue in Minecraft?), but unfortunately I can't debug on Windows.

https://java.com/en/download/help/exception_access.xml

**Comment by ccleve** [comment]
Yup, confirmed that it does work fine on Ubuntu. So, it's probably a limitation of Oracle's implementation of the mmap function on Windows. Probably nothing you can do. Closing the issue...
